import { EventEmitter } from "events"

class ArticleStore extends EventEmitter{
	constructor(){
		super()

		this.articles = [
			{
				title: "My Transformation from ALT to Super ALT",
				author: "Nate G.",
				date: "September 9th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Tips for New ALTs From Grizzled Veterans",
				author: "Rachel W.",
				date: "September 8th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Saving Money in Japan - Slash Your Phone Bill",
				author: "Karl G.",
				date: "September 7th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Hello, World - NihonALT Has Landed",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Test Test Test",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "T2 - Test Test",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Test Test",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "Tt Test",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
			{
				title: "T2 - Test Test",
				author: "Terence M.",
				date: "September 6th, 2017",
				preview: "Lorem ipsum pimpin' sit amizzle, consectetuer adipiscing crunk. Yo sapien velizzle, doggy volutpizzle, suscipizzle crackalackin, gravida vizzle, dizzle. Pellentesque we gonna chung gizzle. Sed erizzle. Fusce izzle dolor dapibus turpizzle tempizzle rizzle. Maurizzle pellentesque nibh dawg turpis.",
				text: [
					"Lorizzle ipsizzle dolor black tellivizzle, check it out adipiscing elit. Nullizzle bling bling velizzle, crunk volutpizzle, suscipizzle quis, gravida vizzle, arcu. Pellentesque things tortizzle. Sizzle erizzle. Shit at ma nizzle dapibus turpis fizzle i saw beyonces tizzles and my pizzle went crizzle. Maurizzle pellentesque nibh izzle you son of a bizzle. Vestibulum in break it down. Pellentesque eleifend rhoncus tellivizzle. In owned that's the shizzle platea i saw beyonces tizzles and my pizzle went crizzle. Hizzle dapibizzle. Crunk nizzle sizzle, pretium sizzle, its fo rizzle fo, eleifend vitae, nunc. Daahng dawg suscipizzle. Integer sempizzle gangster da bomb.",
					"Donizzle break it down shut the shizzle up dang. Phasellizzle bow wow wow elit fo shizzle mammasay mammasa mamma oo sa fo tincidunt. Cool ma nizzle nizzle. Boofron in lacus rizzle elementizzle tristique. Mofo things break it down sizzle its fo rizzle mammasay mammasa mamma oo sa ultricizzle porta. Yo mamma yippiyo shiznit, ultricizzle at, hendrerizzle brizzle, sheezy bow wow wow, check out this. Etizzle velit break yo neck, yall, bow wow wow cool, pharetra nizzle, dictizzle i saw beyonces tizzles and my pizzle went crizzle, sizzle. Sheezy neque. Bizzle shit. Izzle vitae erizzle ut libero commodo yippiyo. Fusce izzle augue da bomb nibh pot mattizzle. Phasellus shizzle my nizzle crocodizzle sapien nizzle boofron. Suspendisse black leo, fo shizzle sizzle, yippiyo izzle, brizzle nizzle, justo. Donizzle uhuh ... yih! porttitor yippiyo. Nunc boofron, ghetto nizzle ornare tempor, sapien funky fresh tincidunt yippiyo, my shizz shit pede enizzle izzle pizzle. Phasellizzle quam leo, cool izzle, tempus izzle, sempizzle izzle, pimpin'. Ut sure magna vel ipsum. Sed ante shizzlin dizzle, suscipizzle mofo, vestibulum uhuh ... yih!, rutrizzle boofron, velizzle. Mauris a yippiyo. Sed ass magna away amizzle risus iaculizzle sure.",
					"Etizzle tellivizzle away dang augue fo shizzle my nizzle accumsizzle. Aenean fo shizzle mah nizzle fo rizzle, mah home g-dizzle est. Vivamizzle mammasay mammasa mamma oo sa dolor, viverra dope, boofron id, ultricizzle izzle, erat. Shiz ante ipsizzle primis izzle faucibus orci i saw beyonces tizzles and my pizzle went crizzle izzle ultrices posuere Gangster; Donec dolizzle. Check out this faucibizzle. Bow wow wow that's the shizzle blandit quizzle. Fo shizzle rutrizzle pot orci. Shiz facilisizzle. Fo shizzle mah nizzle fo rizzle, mah home g-dizzle sizzle nulla, ma nizzle mah nizzle, scelerisque cool, blandizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, magna.",
					"Nulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. CurabiNulla facilisi. Fizzle faucibus pharetra neque. Tellivizzle vulputate check it out izzle mauris. Cras accumsan odio things ipsizzle. Curabitur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.tur adipiscing rizzle vizzle ass. Crizzle fo, mi shiznit eleifend fo shizzle, dolor bizzle bibendum crunk, eu placerizzle my shizz ghetto gangster shiznit. Etizzle the bizzle, lectizzle et bling bling owned, tellizzle i saw beyonces tizzles and my pizzle went crizzle lacinia dang, a fo shizzle nulla we gonna chung izzle purus. Sure aliquet mattizzle ghetto. In its fo rizzle aliquizzle izzle. Daahng dawg leo enizzle, da bomb nec, facilisis nec, the bizzle fo shizzle, bling bling. Dang eget massa yo mamma risizzle blandizzle dictizzle. Crunk ullamcorpizzle turpizzle shizzlin dizzle sem shizzlin dizzle yo mamma. Shizzlin dizzle fizzle gizzle. Maecenas lacinia. Fizzle fermentizzle fizzle enim. Pellentesque sizzle. Lorem ipsizzle crunk sizzle amizzle, brizzle pimpin' elizzle. Maurizzle urna arcu, convallis egizzle, sagittizzle hizzle, break yo neck, yall ma nizzle, neque. Lorizzle ipsizzle gangsta yo mamma amet, consectetuer things elizzle.",
				]
			},
		]
	}

	getArticles(page){
		if(page === 1) {
			return this.articles.slice(0, 4);
		} else if( page === 2) {
			return this.articles.slice(4, 8);
		} else if( page === 3) {
			return this.articles.slice(8, 12);
		}
	}
}

const articleData = new ArticleStore()
export default articleData